/* EX 01 */

SELECT
	IDCLIENTE AS COD_CLIENTE,
	CONCAT(NOME , ' ' , SOBRENOME) AS NOME,
	EMAIL,
	CASE
		WHEN SEXO = 'M' THEN 'MASCULINO'
		WHEN SEXO = 'F' THEN 'FEMININO'
	END AS SEXO,
	FLOOR(DATEDIFF(DAY, NASCIMENTO, GETDATE()) / 365.25) AS IDADE,
	(SELECT
		MIN(DATA)
	FROM 
		NOTA_FISCAL N
	WHERE 
		C.IDCLIENTE = N.ID_CLIENTE) AS PRIMEIRA_COMPRA,
	(SELECT
		MAX(DATA)
	FROM 
		NOTA_FISCAL N
	WHERE 
		C.IDCLIENTE = N.ID_CLIENTE) AS ULTIMA_COMPRA,
	(SELECT
		CONCAT(RUA , ', ', CIDADE , ' - ' , ESTADO , ', ' , REGIAO)
	FROM
		ENDERECO E
	WHERE
		E.ID_CLIENTE = C.IDCLIENTE) AS ENDERECO
FROM
	CLIENTE C
	
/* EX 02 */

SELECT
	P.IDPRODUTO AS ID,
	P.PRODUTO AS DESCRICAO,
	P.VALOR,
	(SELECT
		C.NOME
	FROM
		CATEGORIA C
	WHERE 
		C.IDCATEGORIA = P.ID_CATEGORIA) AS CATEGORIA,
	(SELECT
		F.NOME
	FROM
		FORNECEDOR F
	WHERE 
		F.IDFORNECEDOR = P.ID_FORNECEDOR) AS FORNECEDOR
FROM 
	PRODUTO P

/* EX 03 */

SELECT
	PR.PRODUTO,
	PR.ID_CATEGORIA,
	PR.VALOR AS VALOR
FROM 
	PRODUTO PR
WHERE 
	PR.VALOR = (	SELECT
						MAX(VALOR) AS VALOR
					FROM 
						PRODUTO P
					WHERE
						PR.ID_CATEGORIA = P.ID_CATEGORIA
					GROUP BY
						P.ID_CATEGORIA
				)
ORDER BY
	1

/* EX 04 */

SELECT
	IT.ID_PRODUTO,
	N.ID_VENDEDOR,
	SUM(IT.QUANTIDADE) AS QTD
FROM 
	ITEM_NOTA IT
INNER JOIN NOTA_FISCAL N
	ON IT.ID_NOTA_FISCAL = N.IDNOTA
GROUP BY
	IT.ID_PRODUTO,
	N.ID_VENDEDOR
HAVING
	SUM(IT.QUANTIDADE) = (	SELECT
								MAX(TAB.QUANT) AS QTD
							FROM (	SELECT
										I.ID_PRODUTO AS IDPROD,
										NF.ID_VENDEDOR AS IDVEND,
										SUM(I.QUANTIDADE) AS QUANT
									FROM 
										ITEM_NOTA I
									INNER JOIN NOTA_FISCAL NF
										ON I.ID_NOTA_FISCAL = NF.IDNOTA
									GROUP BY
										ID_PRODUTO,
										NF.ID_VENDEDOR
									) AS TAB
							WHERE 
								TAB.IDPROD = IT.ID_PRODUTO
							GROUP BY
								TAB.IDPROD)
ORDER BY
	1,
	2

/* EX 05 */

SELECT
	TAB.ANO,
	TAB.MES,
	COUNT(TAB.ID) AS VOLUME,
	SUM(TAB.VALOR) AS FATURAMENTO
FROM
	(	SELECT
			N.IDNOTA AS ID,
			YEAR(N.DATA) AS ANO,
			MONTH(N.DATA) AS MES,
			N.TOTAL AS VALOR
		FROM 
			NOTA_FISCAL N
	) AS TAB
GROUP BY
	TAB.ANO,
	TAB.MES
ORDER BY
	1,
	2
	
/* EX 06 */	
	
SELECT
	F.FORMA AS FORMA_PAGAMENTO,
	(	SELECT
			COUNT(N.IDNOTA)
		FROM
			NOTA_FISCAL N
		WHERE
			F.IDFORMA = N.ID_FORMA
		GROUP BY
			N.ID_FORMA) AS VOLUME,
	(	SELECT
			SUM(NE.TOTAL)
		FROM
			NOTA_FISCAL NE
		WHERE
			F.IDFORMA = NE.ID_FORMA
		GROUP BY
			NE.ID_FORMA) AS FATURAMENTO
FROM
	FORMA_PAGAMENTO F
ORDER BY
	2

SELECT
	TAB.FORMA_PAGAMENTO,
	TAB.VOLUME,
	TAB.FATURAMENTO
FROM
	(	SELECT
			F.FORMA AS FORMA_PAGAMENTO,
			COUNT(N.IDNOTA) AS VOLUME,
			SUM(N.TOTAL) AS FATURAMENTO
		FROM 
			FORMA_PAGAMENTO F
		INNER JOIN NOTA_FISCAL N
			ON F.IDFORMA = N.ID_FORMA
		GROUP BY
			F.FORMA) AS TAB
ORDER BY
	2		
		
/* EX 07 */

SELECT
	YEAR(NF.DATA) AS ANO,
	FORMAT(SUM(NF.TOTAL) , 'C' , 'PT-BR') AS FATURAMENTO,
	(	SELECT
			FORMAT(SUM(NE.TOTAL) , 'C' , 'PT-BR') 
		FROM 
			NOTA_FISCAL NE
		WHERE
			YEAR(NE.DATA) <= YEAR(NF.DATA)
	) AS FAT_ACUMULADO
FROM
	NOTA_FISCAL NF
GROUP BY
	YEAR(NF.DATA)
ORDER BY
	1
