/* EX 01 MUDAR LANG DATA*/

SELECT 
	CONCAT(C.NOME, ' ' , C.SOBRENOME) AS NOME,
	C.SEXO,
	CONVERT(VARCHAR(10), C.NASCIMENTO, 103) AS DATA_NASCIMENTO
	E.RUA,
	E.CIDADE,
	E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE

/* EX 02 */

SELECT
	NOME,
	SOBRENOME,
	FLOOR(DATEDIFF(DAY, NASCIMENTO, GETDATE()) / 365.25) AS IDADE,
	CASE
		WHEN DATEDIFF(YEAR, NASCIMENTO, GETDATE()) >= 15 AND DATEDIFF(YEAR, NASCIMENTO, GETDATE()) < 24 THEN '15 A 24'
		WHEN DATEDIFF(YEAR, NASCIMENTO, GETDATE()) >= 25 AND DATEDIFF(YEAR, NASCIMENTO, GETDATE()) <= 34 THEN '23 A 34'
		WHEN DATEDIFF(YEAR, NASCIMENTO, GETDATE()) >= 35 AND DATEDIFF(YEAR, NASCIMENTO, GETDATE()) <= 44 THEN '35 A 44'
		WHEN DATEDIFF(YEAR, NASCIMENTO, GETDATE()) >= 45 AND DATEDIFF(YEAR, NASCIMENTO, GETDATE()) <= 54 THEN '45 A 54'
		WHEN DATEDIFF(YEAR, NASCIMENTO, GETDATE()) > 55 THEN '55+'
		ELSE 'N/A'
	END AS CLASSIFICACAO	
FROM CLIENTE


/* EX 03 */

SELECT
	C.IDCLIENTE,
	C.NOME,
	FLOOR(DATEDIFF(DAY, C.NASCIMENTO, GETDATE()) / 365.25) AS IDADE,
	(SELECT
		CAST(AVG(FLOOR(DATEDIFF(DAY, C.NASCIMENTO, GETDATE()))) AS INT) / 365.25))
	FROM CLIENTE E) AS MEDIA
FROM CLIENTE C
WHERE 
	FLOOR(DATEDIFF(DAY, C.NASCIMENTO, GETDATE()) / 365.25) > (SELECT
													CAST(AVG(FLOOR(DATEDIFF(DAY, C.NASCIMENTO, GETDATE()))) AS INT) / 365.25))
													FROM CLIENTE E)
													
/* EX 04 */

SELECT
	V.IDVENDEDOR AS ID,
	V.NOME AS GERENTE,
	ISNULL(CAST(V.ID_GERENTE AS VARCHAR) , '-') AS ID_GERENTE,
	E.IDVENDEDOR AS ID_SUBORDINADO,
	E.NOME AS SUBORDINADO
FROM VENDEDOR V
INNER JOIN VENDEDOR E
	ON V.IDVENDEDOR = E.ID_GERENTE
	
/* EX 05 */

SELECT
	V.IDVENDEDOR AS ID,
	V.NOME,
	E.SEXO,
	COUNT(E.ID_GERENTE) AS QTD_SUBORDINADO
FROM VENDEDOR V
INNER JOIN VENDEDOR E
	ON V.IDVENDEDOR = E.ID_GERENTE
GROUP BY 
	V.IDVENDEDOR,
	V.NOME,
	E.SEXO
ORDER BY 
	V.IDVENDEDOR

/* EX 06 COLOCAR TOP 2 */

SELECT 
	CIDADE,
	COUNT(ID_CLIENTE) AS QTD_CLIENTE
FROM ENDERECO
GROUP BY 
	CIDADE
HAVING 
	COUNT(ID_CLIENTE) = (SELECT MAX(QTD_CLIENTES) FROM (SELECT COUNT(ID_CLIENTE) AS QTD_CLIENTES FROM ENDERECO GROUP BY CIDADE) ENDERECO)
	OR COUNT(ID_CLIENTE) = (SELECT 
								MAX(QTD_CLIENTES) 
							FROM (SELECT 
									COUNT(ID_CLIENTE) AS QTD_CLIENTES 
								 FROM ENDERECO
								 WHERE CIDADE != (SELECT 
								CIDADE 
							FROM (SELECT
									CIDADE, 
									COUNT(ID_CLIENTE) AS QT_CL 
								 FROM ENDERECO 
								 GROUP BY 
								 CIDADE) ENDERECO
							GROUP BY 
								CIDADE
							HAVING 
								MAX(QT_CL) = (SELECT MAX(QTD_CLIENTES) FROM (SELECT COUNT(ID_CLIENTE) AS QTD_CLIENTES FROM ENDERECO GROUP BY CIDADE) ENDERECO))
								 GROUP BY 
									CIDADE) ENDERECO)
ORDER BY QTD_CLIENTE DESC
GO

/* EX 07 */

SELECT 
	IDCLIENTE,
	NOME,
	EMAIL
FROM CLIENTE
WHERE EMAIL LIKE '%[0-9]%'

/* EX 08 */

SELECT 
	C.IDCLIENTE,
	C.NOME,
	E.RUA
FROM CLIENTE C
INNER JOIN ENDERECO E
	ON C.IDCLIENTE = E.ID_CLIENTE
WHERE E.RUA LIKE 'R.%'

/* EX 09 */

SELECT 
	REGIAO,
	COUNT(ID_CLIENTE) AS QTD_CLIENTE
FROM ENDERECO
GROUP BY REGIAO
HAVING COUNT(ID_CLIENTE) >= (SELECT
							MAX(QTD_CLIENTE) AS CLIENTES
							FROM (SELECT REGIAO, COUNT(ID_CLIENTE) AS QTD_CLIENTE FROM ENDERECO E GROUP BY REGIAO) ENDERECO)
							
/* EX 10 */

SELECT 
	F.IDFORMA,
	F.FORMA AS FORMA_PAGAMENTO,
	COUNT(N.IDNOTA) AS QTD_VENDAS
FROM FORMA_PAGAMENTO F
INNER JOIN NOTA_FISCAL N
	ON F.IDFORMA = N.ID_FORMA
GROUP BY 
	F.IDFORMA,
	F.FORMA
ORDER BY F.IDFORMA

/* EX 11 */

SELECT
	F.IDFORNECEDOR,
	F.NOME,
	COUNT(P.IDPRODUTO) AS QTD_PRODUTO
FROM FORNECEDOR F
INNER JOIN PRODUTO P
	ON F.IDFORNECEDOR = P.ID_FORNECEDOR
GROUP BY 
	F.IDFORNECEDOR,
	F.NOME
ORDER BY F.IDFORNECEDOR

/* EX 12 */

SELECT
	C.IDCATEGORIA,
	C.NOME AS CATEGORIA,
	COUNT(P.IDPRODUTO) AS QTD_PRODUTO
FROM CATEGORIA C
INNER JOIN PRODUTO P
	ON C.IDCATEGORIA = P.ID_CATEGORIA
GROUP BY 
	C.IDCATEGORIA,
	C.NOME
ORDER BY
	C.IDCATEGORIA

/* EX 13 */

SELECT
	V.IDVENDEDOR,
	V.NOME,
	COUNT(N.IDNOTA) AS QTD_VENDA,
	SUM(P.VALOR) AS TOTAL_VENDIDO
FROM VENDEDOR V
INNER JOIN NOTA_FISCAL N
	ON V.IDVENDEDOR = N.ID_VENDEDOR
INNER JOIN ITEM_NOTA I
	ON N.IDNOTA = I.ID_NOTA_FISCAL
INNER JOIN PRODUTO P
	ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY 
	V.IDVENDEDOR,
	V.NOME
ORDER BY
	V.NOME

/* EX 14 */

SELECT
	DATEPART(YEAR , N.DATA) AS ANO,
	DATEPART(MONTH , N.DATA) AS MES,
	COUNT(N.IDNOTA) AS QTD_VENDA
FROM NOTA_FISCAL N
GROUP BY 
	DATEPART(YEAR , N.DATA),
	DATEPART(MONTH , N.DATA)
ORDER BY 
	ANO,
	MES
	
/* EX 15 */

SELECT
	N.IDNOTA AS NOTA_FISCAL,
	P.PRODUTO,
	P.VALOR,
	I.QUANTIDADE,
	P.VALOR * I.QUANTIDADE AS TOTAL_ITEM
FROM NOTA_FISCAL N
INNER JOIN ITEM_NOTA I
	ON N.IDNOTA = I.ID_NOTA_FISCAL
INNER JOIN PRODUTO P
	ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY 
	N.IDNOTA,
	P.PRODUTO,
	P.VALOR,
	I.QUANTIDADE