/* PROVA BANCO DE DADOS */

/* EX 04 */

SELECT
	C.IDCLIENTE AS 'CÓDIGO',
	CONCAT(C.NOME , ' ' , SOBRENOME) AS NOME,
	CONVERT(VARCHAR(10), C.NASCIMENTO, 103) AS DATA_NASCIMENTO,
	CASE 
		WHEN C.SEXO = 'M' THEN 'MASCULINO'
		WHEN C.SEXO = 'F' THEN 'FEMININO'
	END AS SEXO,
	E.CIDADE,
	E.ESTADO,
	E.REGIAO,
	COUNT(N.IDNOTA) AS VOLUME,
	SUM(N.TOTAL) AS MONTANTE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
INNER JOIN NOTA_FISCAL N
ON C.IDCLIENTE = N.ID_CLIENTE
GROUP BY
	C.IDCLIENTE,
	E.CIDADE,
	E.ESTADO,
	E.REGIAO,
	CONCAT(C.NOME , ' ' , SOBRENOME),
	CONVERT(VARCHAR(10), C.NASCIMENTO, 103),
	CASE 
		WHEN C.SEXO = 'M' THEN 'MASCULINO'
		WHEN C.SEXO = 'F' THEN 'FEMININO'
	END
ORDER BY
	COUNT(N.IDNOTA) ASC,
	SUM(N.TOTAL) ASC


/* EX 05 */

SELECT
	YEAR(N.DATA) AS ANO,
	CONCAT(DATEPART(QUARTER, N.DATA) , 'º TRIM') AS TRIMESTRE
	FORMAT(SUM(I.TOTAL), 'C', 'pt-br') AS RECEITA_TOTAL,
	FORMAT(SUM(P.CUSTO_MEDIO * I.QUANTIDADE) , 'C', 'pt-br') AS CUSTO_TOTAL,
	FORMAT(SUM(I.TOTAL) - SUM(P.CUSTO_MEDIO * I.QUANTIDADE) , 'C', 'pt-br') AS LUCRO_TOTAL,
	CONVERT(VARCHAR , CAST(((SUM(I.TOTAL) - SUM(P.CUSTO_MEDIO * I.QUANTIDADE)) / SUM(I.TOTAL)) * 100 AS DECIMAL(10,2))) + '%' AS MARGEM_LUCRO
FROM 
	NOTA_FISCAL N
	INNER JOIN ITEM_NOTA I
		ON N.IDNOTA = ID_NOTA_FISCAL
	INNER JOIN PRODUTO P
		ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY
	YEAR(N.DATA),
	CONCAT(DATEPART(QUARTER, N.DATA) , 'º TRIM')
HAVING
	((SUM(I.TOTAL) - SUM(P.CUSTO_MEDIO * I.QUANTIDADE)) / SUM(I.TOTAL)) * 100 >= 26
ORDER BY
	ANO,
	TRIMESTE