/* EX 01 */

SELECT
	C.IDCLIENTE,
	C.NOME
FROM NOTA_FISCAL N
RIGHT JOIN CLIENTE C
ON N.ID_CLIENTE = C.IDCLIENTE
WHERE 
	N.ID_CLIENTE IS NULL
GO

/* EX 02 */

SELECT TOP 10
	C.IDCLIENTE,
	C.NOME,
	COUNT(N.ID_CLIENTE) AS VOLUME
FROM NOTA_FISCAL N 
INNER JOIN CLIENTE C
ON N.ID_CLIENTE = C.IDCLIENTE
GROUP BY 
	C.IDCLIENTE,
	C.NOME
ORDER BY
	COUNT(N.IDNOTA) DESC
GO

/* EX 03 */

SELECT
	REGIAO,
	COUNT(N.IDNOTA) AS VOLUME,
	SUM(N.TOTAL) AS MONTANTE,
	CASE
		WHEN MONTH(DATA) >= 1 AND MONTH(DATA) <= 3 THEN '1'
		WHEN MONTH(DATA) >= 4 AND MONTH(DATA) <= 6 THEN '2'
		WHEN MONTH(DATA) >= 7 AND MONTH(DATA) <= 9 THEN '3'
		WHEN MONTH(DATA) >= 10 AND MONTH(DATA) <= 12 THEN '4'
	END AS TRIMESTE
FROM NOTA_FISCAL N
INNER JOIN ENDERECO E
ON N.ID_CLIENTE = E.ID_CLIENTE
GROUP BY
	REGIAO,
	CASE
		WHEN MONTH(DATA) >= 1 AND MONTH(DATA) <= 3 THEN '1'
		WHEN MONTH(DATA) >= 4 AND MONTH(DATA) <= 6 THEN '2'
		WHEN MONTH(DATA) >= 7 AND MONTH(DATA) <= 9 THEN '3'
		WHEN MONTH(DATA) >= 10 AND MONTH(DATA) <= 12 THEN '4'
	END 
ORDER BY
	REGIAO,
	TRIMESTE
	
/* EX 04 */

SELECT
	YEAR(DATA) AS ANO,
	SUM(I.TOTAL) AS RECEITA_TOTAL,
	SUM(P.CUSTO_MEDIO * I.QUANTIDADE) AS CUSTO_TOTAL,
	SUM(I.TOTAL) - SUM(P.CUSTO_MEDIO * I.QUANTIDADE) AS LUCRO_TOTAL,
	((SUM(I.TOTAL) - SUM(P.CUSTO_MEDIO * I.QUANTIDADE)) / SUM(I.TOTAL)) * 100 AS MARGEM_LUCRO
FROM NOTA_FISCAL N
INNER JOIN ITEM_NOTA I
ON N.IDNOTA = ID_NOTA_FISCAL
INNER JOIN PRODUTO P
ON I.ID_PRODUTO = P.IDPRODUTO
GROUP BY 
	YEAR(DATA)
ORDER BY
	YEAR(DATA)