/* 1 EX */

SELECT 
	F.ID_FILME, 
	F.DESCRICAO AS NOME, 
	F.DURACAO, 
	F.VALOR, 
	C.DESCRICAO AS CATEGORIA
FROM 
	FILME F
INNER JOIN CATEGORIA C
	ON F.ID_CATEGORIA = C.ID_CATEGORIA

/* 2 EX */

SELECT 
	F.DESCRICAO, 
	F.DURACAO, 
	F.VALOR, 
	C.DESCRICAO AS CATEGORIA
FROM 
	FILME F
INNER JOIN CATEGORIA C
	ON F.ID_CATEGORIA = C.ID_CATEGORIA
WHERE 
	C.DESCRICAO = 'COMÉDIA'

/* 3 EX */ 

SELECT DISTINCT 
	F.DESCRICAO, 
	F.DURACAO, 
	F.VALOR, 
	C.DESCRICAO AS CATEGORIA, 
	FT.DESCRICAO AS 'DESCRIÇÃO FITA'
FROM 
	FILME F
INNER JOIN CATEGORIA C
	ON F.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FITA FT
	ON F.ID_FILME = FT.ID_FILME
WHERE 
	C.DESCRICAO = 'DRAMA' AND F.DURACAO < 120

/* 4 EX */

SELECT 
	F.DESCRICAO AS NOME_FILME, 
	C.DESCRICAO AS CATEGORIA, 
	FT.DESCRICAO AS DESC_FITA
FROM 
	FILME F
INNER JOIN CATEGORIA C
	ON F.ID_CATEGORIA = C.ID_CATEGORIA
INNER JOIN FITA FT
	ON F.ID_FILME = FT.ID_FILME
INNER JOIN LOCACAO L
	ON FT.ID_FITA = L.ID_FITA
INNER JOIN CLIENTE CL
	ON L.ID_CLIENTE = CL.ID_CLIENTE
WHERE 
	CL.ATIVO = 1

/* 5 EX */

SELECT 
	C.ID_CLIENTE, 
	C.NOME, 
	C.CIDADE, 
	C.CELULAR, 
	C.EMAIL
FROM 
	CLIENTE C
INNER JOIN LOCACAO L
	ON C.ID_CLIENTE = L.ID_CLIENTE
INNER JOIN FITA F
	ON F.ID_FITA = L.ID_FITA
INNER JOIN FILME FM
	ON FM.ID_FILME = F.ID_FILME
INNER JOIN CATEGORIA CT
	ON FM.ID_CATEGORIA = CT.ID_CATEGORIA
WHERE 
	CT.DESCRICAO = 'TERROR'

/* 6 EX */

SELECT DISTINCT 
	C.ID_CATEGORIA, 
	C.DESCRICAO
FROM 
	CATEGORIA C
INNER JOIN FILME F
	ON C.ID_CATEGORIA = F.ID_CATEGORIA
INNER JOIN FITA FT
	ON F.ID_FILME = FT.ID_FILME
INNER JOIN LOCACAO L
	ON FT.ID_FITA = L.ID_FITA
INNER JOIN CLIENTE CL
	ON L.ID_CLIENTE = CL.ID_CLIENTE
WHERE 
	CL.ATIVO = 0

/* 7 EX */

SELECT DISTINCT 
	C.ID_CLIENTE, 
	C.NOME
FROM 
	CLIENTE C
INNER JOIN LOCACAO L
	ON C.ID_CLIENTE = L.ID_CLIENTE

/* 8 EX */

SELECT DISTINCT 
	C.ID_CLIENTE, 
	C.NOME
FROM 
	CLIENTE C
LEFT JOIN LOCACAO L
	ON C.ID_CLIENTE = L.ID_CLIENTE
WHERE 
	L.ID_CLIENTE IS NULL

/* 9 EX */

SELECT 
	C.DESCRICAO AS CATEGORIA, 
	F.DESCRICAO AS NOME_FILME, 
	FT.DESCRICAO AS DESCRICAO_FITA, 
	FT.ID_FITA AS ID_FITA
FROM 
	CATEGORIA C
INNER JOIN FILME F
	ON C.ID_CATEGORIA = F.ID_CATEGORIA
INNER JOIN FITA FT
	ON F.ID_FILME = FT.ID_FILME
LEFT JOIN LOCACAO L
	ON FT.ID_FITA = L.ID_FITA
WHERE 
	L.ID_FITA IS NULL

/* 10 EX */

SELECT DISTINCT 
	FI.ID_FILME AS ID_FILME, 
	FI.DESCRICAO AS NOME_FILME
FROM 
	FILME FI
INNER JOIN FITA FT
	ON FI.ID_FILME = FT.ID_FILME
LEFT JOIN LOCACAO L
	ON FT.ID_FITA = L.ID_FITA
WHERE 
	L.ID_FITA IS NULL 
AND
FI.ID_FILME NOT IN (SELECT F.ID_FILME
						FROM FITA F
					INNER JOIN LOCACAO LO
						ON F.ID_FITA = LO.ID_FITA)