CREATE DATABASE LOCADORA

USE LOCADORA

CREATE TABLE CLIENTE(
	ID_CLIENTE INT IDENTITY(1,1),
	NOME VARCHAR(50) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	LOGRADOURO VARCHAR(50) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(40) NOT NULL,
	CIDADE VARCHAR(45) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	CEP VARCHAR(15) NOT NULL
)
GO

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT IDENTITY(1,1),
	DESCRICAO VARCHAR(100) NOT NULL
)
GO

CREATE TABLE FILME(
	ID_FILME INT IDENTITY(1,1),
	ID_CATEGORIA INT NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	DURACAO INT NOT NULL,
	VALOR DECIMAL(5,2) NOT NULL
)
GO

CREATE TABLE FITA(
	ID_FITA INT IDENTITY(1,1),
	ID_FILME INT NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	DATA_COMPRA DATE NOT NULL,
)
GO

CREATE TABLE LOCACAO(
	ID_CLIENTE INT NOT NULL,
	ID_FITA INT NOT NULL,
	DATA_LOCACAO DATE NOT NULL
)
GO



ALTER TABLE CLIENTE
ADD CONSTRAINT PK_CLIENTE 
PRIMARY KEY (ID_CLIENTE)
GO

ALTER TABLE CLIENTE
ADD EMAIL VARCHAR(30),
TELEFONE VARCHAR(15),
CELULAR VARCHAR(15) NOT NULL,
ATIVO INT NOT NULL 
GO

ALTER TABLE CLIENTE
ADD CONSTRAINT DF_ATIVO
DEFAULT 1 FOR ATIVO

ALTER TABLE CLIENTE
ADD CONSTRAINT UC_CPF
UNIQUE(CPF)

CREATE INDEX IDX_CPF
ON CLIENTE (CPF)
GO

ALTER TABLE CATEGORIA
ADD CONSTRAINT PK_CATEGORIA
PRIMARY KEY (ID_CATEGORIA)
GO

ALTER TABLE FILME
ADD CONSTRAINT PK_FILME
PRIMARY KEY (ID_FILME)
GO

ALTER TABLE FILME
ADD CONSTRAINT FK_CATEGORIA_FILME
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA)
GO

ALTER TABLE FITA
ADD CONSTRAINT PK_FITA
PRIMARY KEY(ID_FITA)
GO

ALTER TABLE FITA
ADD CONSTRAINT FK_FILME_FITA
FOREIGN KEY(ID_FILME) REFERENCES FILME (ID_FILME)
GO

ALTER TABLE LOCACAO
ADD CONSTRAINT PK_CLIENTE_LOCACAO
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE)
GO

ALTER TABLE LOCACAO
ADD CONSTRAINT PK_FITA_LOCACAO
FOREIGN KEY (ID_FITA) REFERENCES FITA (ID_FITA)
GO

ALTER TABLE LOCACAO
ADD CONSTRAINT PK_LOCACAO
PRIMARY KEY (ID_CLIENTE , ID_FITA , DATA_LOCACAO)
GO

ALTER TABLE LOCACAO
ADD CONSTRAINT DF_DATA_LOCACAO
DEFAULT GETDATE() FOR DATA_LOCACAO

/* DQL */

SELECT ID_CATEGORIA AS ID, DESCRICAO AS CATEGORIA
FROM CATEGORIA

SELECT DESCRICAO AS NOME, DURACAO AS 'DURAÇÃO', VALOR AS 'PREÇO'
FROM FILME

SELECT NOME AS CLIENTE, EMAIL, TELEFONE, CELULAR
FROM CLIENTE

SELECT NOME AS CLIENTE, LOGRADOURO AS RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP
FROM CLIENTE
ORDER BY NOME

SELECT ID_CLIENTE AS ID, NOME AS CLIENTE, EMAIL, CPF, DATA_NASCIMENTO, 
	   LOGRADOURO AS RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP
FROM CLIENTE
WHERE EMAIL = 'pedro.alves@email.com'

SELECT DESCRICAO AS CATEGORIA
FROM CATEGORIA
ORDER BY DESCRICAO DESC

SELECT DESCRICAO AS CATEGORIA
FROM CATEGORIA
WHERE DESCRICAO LIKE 'A%'

SELECT ID_FILME AS ID, DESCRICAO AS NOME_FILME
FROM FILME
WHERE VALOR > 10

SELECT ID_FILME AS ID, DESCRICAO AS NOME_FILME
FROM FILME
WHERE DURACAO <= 120

SELECT ID_FILME AS ID, DESCRICAO AS NOME_FILME
FROM FILME
WHERE DURACAO > 130

SELECT NOME AS CLIENTE, CIDADE, ESTADO
FROM CLIENTE

SELECT 
	ID_FITA AS ID, 
	ID_FILME, 
	DESCRICAO AS NOME_FITA
FROM FITA
WHERE 
	DATEDIFF(MONTH , '2019/06/30' , DATA_COMPRA) <= 0 

SELECT ID_CLIENTE AS CLIENTE, ID_FITA AS FITA
FROM LOCACAO
WHERE DATEPART(MONTH , DATA_LOCACAO) = 11 AND DATEPART(YEAR , DATA_LOCACAO) = 2019

SELECT ID_FITA AS ID, DESCRICAO AS NOME_FITA
FROM FITA
WHERE DATEPART(MONTH , DATA_COMPRA) = 1 AND DATEPART(YEAR , DATA_COMPRA) = 2019

SELECT ID_CLIENTE AS ID, NOME AS CLIENTE, EMAIL, CPF, DATA_NASCIMENTO, 
	   LOGRADOURO AS RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP
FROM CLIENTE
WHERE NOME LIKE ' %ALVES%'

SELECT ID_CLIENTE AS ID, NOME AS CLIENTE, EMAIL, CPF, DATA_NASCIMENTO, 
	   LOGRADOURO AS RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP
FROM CLIENTE
WHERE CIDADE = 'CAMPO MOURÃO'

SELECT ID_CLIENTE AS ID, NOME AS CLIENTE, EMAIL, CPF, DATA_NASCIMENTO, 
	   LOGRADOURO AS RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP
FROM CLIENTE
WHERE BAIRRO = 'CENTRO' AND CIDADE = 'CAMPO MOURÃO'

SELECT ID_CLIENTE AS ID, NOME AS CLIENTE, EMAIL, CPF, DATA_NASCIMENTO, 
	   LOGRADOURO AS RUA, NUMERO, BAIRRO, CIDADE, ESTADO, CEP
FROM CLIENTE
WHERE DATEPART(YEAR , DATA_NASCIMENTO) >= 1992
ORDER BY NOME

SELECT CIDADE , ESTADO
FROM CLIENTE
WHERE ATIVO = 1
ORDER BY 1

UPDATE TABLE CLIENTE
SET ATIVO = 0
WHERE ID_CLIENTE = 2

ALTER TABLE LOCACAO
ADD DATA_DEVOLUCAO DATETIME
GO

ALTER TABLE LOCACAO
ADD CONSTRAINT DF_DATA_DEVOLUCAO
DEFAULT GETDATE() FOR DATA_DEVOLUCAO
GO

SELECT ID_CLIENTES AS ID, NOME AS CLIENTE
FROM CLIENTE
WHERE ATIVO = 0 AND CIDADE = 'CAMPO MOURÃO'

